apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
data:
  config.hcl: |-
    disable_mlock = true
    ui = true

    listener "tcp" {
      tls_disable = 1
      address = "0.0.0.0:8200"
      cluster_address = "0.0.0.0:8201"
    }
    storage "file" {
      path = "/vault/data"
    }
