apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: null
  deletionGracePeriodSeconds: 0
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    usage: vault-vault
  name: vault-vault
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /nfs/vault/vault
    server: 192.168.2.254
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status: {}
